"""
Supabase vector store — stores and retrieves document chunks using
Supabase's pgvector extension (PostgreSQL).

Embeddings are generated by the `rag.embeddings` module (Google Gemini)
before being inserted. All heavy AI computation happens in the cloud;
this module is purely responsible for database I/O.

Public API (identical signatures to the old Qdrant implementation so
that no other files in the project need to change):
    add_documents(session_id, chunks)
    similarity_search(session_id, query, k) -> List[dict]
    has_documents(session_id) -> bool
    list_document_names(session_id) -> List[str]
    delete_document(session_id, filename)
"""
from __future__ import annotations

import logging
from functools import lru_cache

from supabase import create_client, Client

import config
from rag import embeddings as emb

logger = logging.getLogger(__name__)

TABLE = "document_chunks"


# ── Singleton Supabase client ─────────────────────────────────────────────────

@lru_cache(maxsize=1)
def _get_client() -> Client:
    if not config.SUPABASE_URL or not config.SUPABASE_KEY:
        raise ValueError(
            "SUPABASE_URL and SUPABASE_KEY must be set in your .env file."
        )
    logger.info("Connecting to Supabase at: %s", config.SUPABASE_URL)
    return create_client(config.SUPABASE_URL, config.SUPABASE_KEY)


# ── Document operations ───────────────────────────────────────────────────────

def add_documents(session_id: str, chunks: list[dict]) -> None:
    """
    Embed and store chunks in Supabase pgvector.
    chunks: list of {"text": str, "source": str}

    Steps:
      1. Send all chunk texts to Gemini API → get 768-dim float vectors
      2. Bulk insert rows (content, source, session_id, embedding) into Supabase
    """
    client = _get_client()

    texts = [c["text"] for c in chunks]
    sources = [c["source"] for c in chunks]

    # Step 1: Generate embeddings in the cloud (zero local RAM/CPU usage)
    vectors = emb.embed_texts(texts)

    # Step 2: Build rows for bulk insert
    rows = [
        {
            "session_id": session_id,
            "content": text,
            "source": source,
            "embedding": vector,
        }
        for text, source, vector in zip(texts, sources, vectors)
    ]

    client.table(TABLE).insert(rows).execute()
    logger.info("Inserted %d chunks into Supabase for session %s", len(rows), session_id)


def similarity_search(
    session_id: str, query: str, k: int = config.TOP_K_RESULTS
) -> list[dict]:
    """
    Return the top-k most relevant chunks for a query.
    Returns list of {"text": str, "source": str}

    Steps:
      1. Embed the query text via Gemini API
      2. Call the Supabase RPC function `match_document_chunks` (cosine similarity)
    """
    client = _get_client()

    # Step 1: Embed the query in the cloud
    query_vector = emb.embed_query(query)

    # Ensure match_count has a safe integer fallback for client.rpc
    try:
        match_count = int(k)
    except (TypeError, ValueError):
        match_count = 5

    # Step 2: Call the pgvector similarity search RPC function
    response = client.rpc(
        "match_document_chunks",
        {
            "query_embedding": query_vector,
            "match_threshold": config.SIMILARITY_THRESHOLD,
            "match_count": match_count,
            "filter_session_id": session_id,
        },
    ).execute()

    return [
        {
            "text": row["content"],
            "source": row["source"],
        }
        for row in (response.data or [])
    ]


def has_documents(session_id: str) -> bool:
    """Return True if any document chunks exist for this session."""
    client = _get_client()
    response = (
        client.table(TABLE)
        .select("id", count="exact")
        .eq("session_id", session_id)
        .limit(1)
        .execute()
    )
    return (response.count or 0) > 0


def list_document_names(session_id: str) -> list[str]:
    """Return a sorted list of unique document filenames for this session."""
    client = _get_client()
    response = (
        client.table(TABLE)
        .select("source")
        .eq("session_id", session_id)
        .execute()
    )
    names = {row["source"] for row in (response.data or []) if row.get("source")}
    return sorted(names)


def delete_document(session_id: str, filename: str) -> None:
    """Remove all chunks belonging to a specific document from this session."""
    client = _get_client()
    client.table(TABLE).delete().eq("session_id", session_id).eq("source", filename).execute()
    logger.info("Deleted document '%s' from session %s", filename, session_id)


def collection_exists(session_id: str) -> bool:
    """Return True if any document chunks exist for this session (alias for backward compatibility)."""
    return has_documents(session_id)
